<%@ page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>JSP - Hello World</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.6.1.js" integrity="sha256-3zlB5s2uwoUzrXK3BT7AX3FyvojsraNFxCc2vC/7pNI=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@10"></script>
    <style>
        html{
            width: 100%;
            height: 100%;
        }
        body{
            width: 100%;
            height: 100%;
        }
        #wifi-table{
            width: 100%;
        }
        #loadingDiv{
            position: absolute;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            background: black;
            opacity: 10%;
        }
        #loading{
            position: absolute;
            top:50%;
            left: 50%;
            transform: translate(-50%,-50%);
        }

    </style>
    <style>
        @keyframes ldio-pi1l96of9o {
            0% { opacity: 1 }
            100% { opacity: 0 }
        }
        .ldio-pi1l96of9o div {
            left: 130.19px;
            top: 58.17px;
            position: absolute;
            animation: ldio-pi1l96of9o linear 1s infinite;
            background: #689cc5;
            width: 16.62px;
            height: 33.24px;
            border-radius: 0px / 0px;
            transform-origin: 8.31px 80.33px;
        }.ldio-pi1l96of9o div:nth-child(1) {
             transform: rotate(0deg);
             animation-delay: -0.9s;
             background: #689cc5;
         }.ldio-pi1l96of9o div:nth-child(2) {
              transform: rotate(36deg);
              animation-delay: -0.8s;
              background: #689cc5;
          }.ldio-pi1l96of9o div:nth-child(3) {
               transform: rotate(72deg);
               animation-delay: -0.7s;
               background: #689cc5;
           }.ldio-pi1l96of9o div:nth-child(4) {
                transform: rotate(108deg);
                animation-delay: -0.6s;
                background: #689cc5;
            }.ldio-pi1l96of9o div:nth-child(5) {
                 transform: rotate(144deg);
                 animation-delay: -0.5s;
                 background: #689cc5;
             }.ldio-pi1l96of9o div:nth-child(6) {
                  transform: rotate(180deg);
                  animation-delay: -0.4s;
                  background: #689cc5;
              }.ldio-pi1l96of9o div:nth-child(7) {
                   transform: rotate(216deg);
                   animation-delay: -0.3s;
                   background: #689cc5;
               }.ldio-pi1l96of9o div:nth-child(8) {
                    transform: rotate(252deg);
                    animation-delay: -0.2s;
                    background: #689cc5;
                }.ldio-pi1l96of9o div:nth-child(9) {
                     transform: rotate(288deg);
                     animation-delay: -0.1s;
                     background: #689cc5;
                 }.ldio-pi1l96of9o div:nth-child(10) {
                      transform: rotate(324deg);
                      animation-delay: 0s;
                      background: #689cc5;
                  }
        .loadingio-spinner-spinner-oann461p6r8 {
            width: 277px;
            height: 277px;
            display: inline-block;
            overflow: hidden;
            background: none;
        }
        .ldio-pi1l96of9o {
            width: 100%;
            height: 100%;
            position: relative;
            transform: translateZ(0) scale(1);
            backface-visibility: hidden;
            transform-origin: 0 0; /* see note above */
        }
        .ldio-pi1l96of9o div { box-sizing: content-box; }
        /* generated by https://loading.io/ */
    </style>
</head>
<body>
<h1 class="align-items-center center">와이파이 정보 구하기</h1>
<a href="/">홈</a> | <a href="#" onclick="getHistory();" data-bs-toggle="modal" data-bs-target="#exampleModal">위치 히스토리 목록</a> | <a href="./wifi/saveAll" id="getAPIData">Open API 와이파이 정보 가져오기</a>
<form method="get">
    LAT : <input type="text" id="latitude" value="0.0">, LNT : <input type="text" id="longitude" value="0.0">
    <button type="button" class="btn btn-primary" id="getMyLocation">내 위치 가져오기</button>
    <button type="button" class="btn btn-primary" id="getWifiInfo">근처 WIFI 정보 가져오기</button>
</form>
<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg modal-dialog-scrollable">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel">위치 히스토리 목록</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <table class="table table-hover">
                    <thead>
                        <tr>
                            <td>ID</td>
                            <td>X좌표</td>
                            <td>Y좌표</td>
                            <td>조회일자</td>
                            <td>비고</td>
                        </tr>
                    </thead>
                    <tbody id="history-body">
                        <tr>
                            <td>1</td>
                            <td>37.2680521</td>
                            <td>127.0301429</td>
                            <td>2022-10-18 14:21:41</td>
                            <td><button type="button" class="btn btn-primary btn-sm">삭제</button></td>
                        </tr>
                    </tbody>
                </table>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>
<div id="loadingDiv">
</div>
    <div class="loadingio-spinner-spinner-oann461p6r8" id="loading"><div class="ldio-pi1l96of9o">
    <div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div></div>
    </div>
<table id="wifi-table" class="table table-hover">
    <thead>
        <tr class="text-center">
            <th>거리(Km)</th>
            <th>관리번호</th>
            <th>자치구</th>
            <th>와이파이명</th>
            <th>도로명주소</th>
            <th>상세주소</th>
            <th>설치위치(층)</th>
            <th>설치유형</th>
            <th>설치기관</th>
            <th>서비스구분</th>
            <th>망종류</th>
            <th>설치년도</th>
            <th>실내외구분</th>
            <th>WIFI접속환경</th>
            <th>X좌표</th>
            <th>Y좌표</th>
            <th>작업일자</th>
        </tr>
    </thead>
    <tbody id="wifi-body">
    </tbody>
</table>
<script>
    $(function() {
        $('#loading').hide();
        $('#loadingDiv').hide();
    });
    $('#getAPIData').on('click',function (){
        $('#loading').show();
        $('#loadingDiv').show();
    });

    function getHistory(){
        $('#history-body').html('');
        // history-body
        $.ajax({
            url: "/wifi/history",
            type: "get",
            dataType: "json",
            success: function(result) {
                console.log(result);
                if (result.length > 0){
                    for (let i = 0; i < result.length; i++) {
                        let list;
                        list = '<tr>';

                        list += '<td>' + result[i].id +'<td>';
                        list += '<td>' + result[i].x +'<td>';
                        list += '<td>' + result[i].y +'<td>';
                        list += '<td>' + result[i].date +'<td>';
                        list += '<td><button type="button" class="btn btn-primary btn-sm" value="'+ result[i].id+'" onclick="historyDelete(' + result[i].id +')">삭제</button></td>';
                        list += '</tr>';
                        $('#history-body').append(list);
                    }
                }else {
                    let list = '<tr><td colspan="5">조회 된 내용이 없습니다.</td></tr>';
                    $('#history-body').append(list);
                }

            },
            error: function(xhr, status, error) {
                console.log('실패' + error);
            }
        });
    }

    function historyDelete(id){
        $.ajax({
            url: "/wifi/deleteHistory",
            type: "get",
            data: { "id" : id },
            success: function(result) {
                getHistory();
            },
            error: function(xhr, status, error) {
                console.log('실패' + error);
                getHistory();
            }
        });
    }

    $('#getMyLocation').on('click',function (){
        $('#loading').show();
        $('#loadingDiv').show();
        if (navigator.geolocation) {
            navigator.geolocation.getCurrentPosition (function(pos) {
                $('#latitude').val(pos.coords.latitude);
                $('#longitude').val(pos.coords.longitude);
                $('#loading').hide();
                Swal.fire(
                    '내 위치 가져오기',
                    "",
                    'success'
                )
                $('#loading').hide();
                $('#loadingDiv').hide();
            });

        } else {
            Swal.fire(
                '내 위치 가져오기',
                "",
                'error'
            )
            $('#loading').hide();
            $('#loadingDiv').hide();
        }
    });

    $('#getWifiInfo').on('click',function (){
        $('#loading').show();
        $('#loadingDiv').show();
        let x = $('#latitude').val();
        let y = $('#longitude').val();
        $.ajax({
            url: "/wifi/saveHistory",
            type: "get",
            data: {"x":x , "y":y},
            dataType: "text",
            success: function(result) {
                if (result > 0) {
                    $.ajax({
                        url: "/wifi/getInfo",
                        type: "get",
                        data: {"x":x , "y":y},
                        dataType: "json",
                        success: function(result) {
                            $('#wifi-body').html('');
                            if (result.length > 1) {
                                for (let i = 0; i < result.length; i++) {
                                    let list;
                                    list = '<tr>';
                                    list += '<td>test</td>';
                                    list += '<td>'+ result[i].no +'</td>';
                                    list += '<td>'+ result[i].gu +'</td>';
                                    list += '<td>'+ result[i].name +'</td>';
                                    list += '<td>'+ result[i].address1 +'</td>';
                                    list += '<td>'+ result[i].address2 +'</td>';
                                    list += '<td>'+ result[i].instLocation +'</td>';
                                    list += '<td>'+ result[i].instType +'</td>';
                                    list += '<td>'+ result[i].instAgency +'</td>';
                                    list += '<td>'+ result[i].serviceType +'</td>';
                                    list += '<td>'+ result[i].networkType +'</td>';
                                    list += '<td>'+ result[i].instYear +'</td>';
                                    list += '<td>'+ result[i].inOutType +'</td>';
                                    list += '<td>'+ result[i].accessType +'</td>';
                                    list += '<td>'+ result[i].x +'</td>';
                                    list += '<td>'+ result[i].y +'</td>';
                                    list += '<td>'+ result[i].date +'</td>';
                                    list += '</tr>';
                                    $('#wifi-body').append(list);
                                }
                                Swal.fire(
                                    '근처 WIFI 정보 가져오기',
                                    "",
                                    'success'
                                )
                                $('#loading').hide();
                                $('#loadingDiv').hide();
                            } else {
                                let list = '<tr><td colspan="17" class="text-center">조회 된 내용이 없습니다.</td></tr>';
                                $('#wifi-body').append(list);
                                Swal.fire(
                                    '근처 WIFI 정보 가져오기',
                                    "",
                                    'success'
                                )
                                $('#loading').hide();
                                $('#loadingDiv').hide();
                            }
                        },
                        error: function(xhr, status, error) {
                            console.log('실패' + error);
                        }
                    });
                }
            },
            error: function(xhr, status, error) {
                console.log('실패' + error);
            }
        });
        console.log(x);
        console.log(y);
    });
</script>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"
        integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.min.js"
        integrity="sha384-IDwe1+LCz02ROU9k972gdyvl+AESN10+x7tBKgc9I5HFtuNz0wWnPclzo6p9vxnk"
        crossorigin="anonymous"></script>
</body>
</html>